services:
  searchclient:
    build:
      context: ../../src/ScriptureSearch/
      target: final
    environment:
      ASPNETCORE_URLS: http://+:8080
    restart: always

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - index_data:/chroma/chroma/
    restart: always

  searchapi:
    image: cwighty/versio:latest
    restart: always

  swag:
    container_name: w-swag
    image: lscr.io/linuxserver/swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=versio.duckdns.org
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=${DUCKDNSTOKEN}
      - STAGING=false
    volumes:
      - swag:/config
      - ./swag-default.conf:/config/nginx/site-confs/default.conf
    ports:
      - 0.0.0.0:443:443
    restart: unless-stopped

volumes:
  index_data:
    driver: local
  swag:
